---
- name: Set mattermost_file_public_link_salt variable
  ansible.builtin.import_tasks: setting/token/file_public_link_salt.yml
  when: not mattermost_file_public_link_salt
- name: Set mattermost_sql_at_rest_encrypt_key variable
  ansible.builtin.import_tasks: setting/token/sql_at_rest_encrypt_key.yml
  when: not mattermost_sql_at_rest_encrypt_key


- name: Create/update Mattermost setting file
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ mattermost_home }}/config/config.json"
    mode: "0644"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
  notify: restart mattermost
