---
- name: Include database setup task
  when: mattermost_db_cfg.host in ['localhost', '127.0.0.1']
  block:
    - name: Setup databse
      ansible.builtin.include_tasks: database/{{ mattermost_db_cfg.type }}.yml
    - name: Execute setup database commands
      become: true
      become_user: "{{ mattermost_user }}"
      environment:
        MM_CONFIG: "{{ mattermost_dsn }}"
      block:
        - name: Execute database init
          ansible.builtin.command:
            cmd: "{{ mattermost_home }}/bin/mattermost db init"
            chdir: "{{ mattermost_home }}"
            creates: "{{ mattermost_home }}/mattermost_db_init"
        - name: Create db init command execule file
          ansible.builtin.file:
            path: "{{ mattermost_home }}/mattermost_db_init"
            state: touch
            mode: "0644"
            access_time: preserve
            modification_time: preserve
        - name: Execute database migrate
          ansible.builtin.command:
            cmd: "{{ mattermost_home }}/bin/mattermost db migrate"
            chdir: "{{ mattermost_home }}"
          when: update_mattermost is changed
