---
- name: Generate mattermost_file_public_link_salt token
  ansible.builtin.import_tasks: setting/tokens/file_public_link_salt.yml
  when: not mattermost_file_public_link_salt
- name: Generate mattermost_sql_at_rest_encrypt_key token
  ansible.builtin.import_tasks: setting/tokens/sql_at_rest_encrypt_key.yml
  when: not mattermost_sql_at_rest_encrypt_key
- name: Find platform task file
  ansible.builtin.set_fact:
    include_task_file: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - tasks/setting
- name: Create/update setting
  ansible.builtin.include_tasks: "{{ include_task_file }}"
  when: include_task_file | length > 0
