---
- name: Add Mattermost group
  ansible.builtin.group:
    name: "{{ mattermost_group }}"
    system: true
- name: Add Mattermost user
  ansible.builtin.user:
    name: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    system: true
- name: Create install directory
  ansible.builtin.file:
    path: "{{ mattermost_home }}"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    state: directory
    mode: "0755"
