---
- name: restart mattermost
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: mattermost
- name: reload mattermost
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: reloaded
    name: mattermost
