---
# - name: Restart mattermost
#   ansible.builtin.systemd:
#     state: restarted
#     name: mattermost
# - name: Reload mattermost
#   ansible.builtin.systemd:
#     state: reloaded
#     name: mattermost
