---
- name: Install database dependency packages(PostgreSQL)
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2
      - acl
- name: Setup database
  become: true
  become_user: postgres
  block:
    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ mattermost_db_cfg.name }}"
        encoding: "{{ mattermost_db_cfg.encoding | default('UTF8') }}"
    - name: Create database user
      community.postgresql.postgresql_user:
        name: "{{ mattermost_db_cfg.user }}"
        password: "{{ mattermost_db_cfg.password }}"
        db: "{{ mattermost_db_cfg.name }}"
