---
- name: Check token file
  ansible.builtin.stat:
    path: "{{ mattermost_home }}/config/file_public_link_salt"
  register: token_file_stat_result
- name: Generate token
  ansible.builtin.set_fact:
    mattermost_file_public_link_salt: "{{ lookup('community.general.random_string', length=32) }}"
  when: not token_file_stat_result.stat.exists
- name: Get generated token
  when: token_file_stat_result.stat.exists
  block:
    - name: Get generated token
      ansible.builtin.command:
        cmd: cat {{ mattermost_home }}/config/file_public_link_salt
        removes: "{{ mattermost_home }}/config/file_public_link_salt"
      register: internal_token_result
      changed_when: false
    - name: Set mattermost_file_public_link_salt variable
      ansible.builtin.set_fact:
        mattermost_file_public_link_salt: "{{ internal_token_result.stdout }}"
- name: Add/update generated token file
  ansible.builtin.template:
    src: token.j2
    dest: "{{ mattermost_home }}/config/file_public_link_salt"
    mode: "0644"
  vars:
    token_value: "{{ mattermost_file_public_link_salt }}"
