---
- name: Check token file
  ansible.builtin.stat:
    path: "{{ mattermost_root }}/config/file_public_link_salt"
  register: token_file_stat_result
- name: Generate token
  ansible.builtin.set_fact:
    mattermost_file_public_link_salt: "{{ lookup('community.general.random_string', length=32, special=False) }}"
  when: not token_file_stat_result.stat.exists
- name: Get generated token
  when: token_file_stat_result.stat.exists
  block:
    - name: Get generated token
      ansible.builtin.command:
        cmd: cat {{ mattermost_root }}/config/file_public_link_salt
        removes: "{{ mattermost_root }}/config/file_public_link_salt"
      register: internal_token_result
      changed_when: false
    - name: Set mattermost_file_public_link_salt variable
      ansible.builtin.set_fact:
        mattermost_file_public_link_salt: "{{ internal_token_result.stdout }}"
