---
- name: Get mattermost latest version
  when: mattermost_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/mattermost/mattermost-server/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: set mattermost_version variable
      ansible.builtin.set_fact:
        mattermost_version: "{{ latest_releases.json.tag_name[1:] }}"
- name: Set variables
  ansible.builtin.set_fact:
    mattermost_download_file: mattermost-{{ mattermost_version }}-{{ ansible_facts['system'] | lower }}-{{ architecture_files[ansible_facts['architecture']] }}
  vars:
    architecture_files:
      x86_64: amd64
- name: Download archive file
  ansible.builtin.get_url:
    url: https://releases.mattermost.com/{{ mattermost_version }}/{{ mattermost_download_file }}.tar.gz
    dest: /usr/local/src/mattermost.tar.gz
    mode: "0644"
  register: update_mattermost
  notify: restart mattermost
- name: Unarchive download file
  ansible.builtin.unarchive:
    src: /usr/local/src/mattermost.tar.gz
    extra_opts:
      - --strip-components=1
      - --exclude=config/config.json
    dest: "{{ mattermost_home }}"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    remote_src: true
  changed_when: false
